### ISSUE TITLE
palinode.series invokes run list with wrong parameters

### ISSUE THREAD

**Issue by kakashif** [GannettDigital/palinode#18]
This might be an expected behavior.  When calling a list of functions in palinode.series, if a function calls the callback without any parameters, the next function's first parameter is a type of function.

```
function fun1(data, cb)  {
  cb(); // or cb(undefined);
}

function fun2(data, cb) {
  assert(typeof data === 'function', false);
}

palinode.series([fun1, fun2], someCallback);
```

**Comment by jhaugh42** [comment]
Series passes the result parameter to the subsequent function, so you should use it in circumstances where the next task requires some output from the previous task.  

Are you suggesting we need an `each` implementation that does one task at a time, in the order specified, without passing the result of the previous task to the next task?  That is totally possible.
